server:
  port: 5000
  servlet:
    contextPath: /makhtab
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/makhtab
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    maximumPoolSize : 500
    idleTimeout: 120000
    connectionTimeout: 300000
    leakDetectionThreshold: 300000
  servlet:
    multipart:
      max-file-size: 126MB
      max-request-size: 126MB
     

